import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#13131b",
        "on-background": "#e4e1ed",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        "surface-container": "#1f1f27",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#e4e1ed",
        "inverse-on-surface": "#303038",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        secondary: "#6bde80",
        "on-secondary": "#003913",
        "secondary-container": "#2fa54f",
        "on-secondary-container": "#003210",
        tertiary: "#ffb867",
        "on-tertiary": "#482900",
        "tertiary-container": "#cd7f00",
        "on-tertiary-container": "#3f2300",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#88fb99",
        "secondary-fixed-dim": "#6bde80",
        "on-secondary-fixed": "#002108",
        "on-secondary-fixed-variant": "#00531f",
        "tertiary-fixed": "#ffddba",
        "tertiary-fixed-dim": "#ffb867",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#673d00",
        "surface-variant": "#34343d",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        display: ["var(--font-display)", "Plus Jakarta Sans", "sans-serif"],
      },
      transitionTimingFunction: {
        liquid: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      animation: {
        "liquid-slow": "liquid 8s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
